name: backend-deploy-develop
on:
  pull_request:
      types:
        - opened
      branches:
        - 'feature/**'
        - 'hotfix/**'
        - 'develop'
        - 'devops'

jobs:
  code-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Test With Gradlew
        run: ./gradlew test